<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Themetour extends CI_Controller 
{
	function __construct()
	{
		parent::__construct();
		$this->load->helper('url');
		session_start();
	}
	function index()
	{
		$sorttype='';
		$this->load->model('show');
		$num=$this->show->totaltour('',$sorttype);
		$per_page=8;
		$count=ceil($num/$per_page);
		$page=$this->uri->segment(3);
		if($page=='')
		{
			$page=1;
		}
		$action=$this->uri->segment(4);
		$sort=$this->uri->segment(5);
		if(isset($page) && $page!='')
		{
			$start=($page*$per_page)-$per_page;
		}
		else
		{
			$start=0;
		}
		
		if(isset($action) &&$action!='')
		{
			$data['page']['first']='themetour/index/1/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['end']='themetour/index/'.$count.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			if($page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if($page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='termtour/index/'.$i.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/index/'.$pagepre.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['next']='themetour/index/'.$pagenext.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
		}
		else
		{
			$data['page']['first']='themetour/index/1'.$this->config->item('url_suffix');
			$data['page']['end']='themetour/index/'.$count.$this->config->item('url_suffix');
			if(isset($page) && $page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if(isset($page) && $page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='themetour/index/'.$i.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/index/'.$pagepre.$this->config->item('url_suffix');
			$data['page']['next']='themetour/index/'.$pagenext.$this->config->item('url_suffix');
		}
		if(isset($sort) && $sort!='')
		{
			if($sort=='asc')
			{
				$data['sortday']='themetour/index/1/days/desc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/index/1/price/desc'.$this->config->item('url_suffix');
			}
			else
			{
				$data['sortday']='themetour/index/1/days/asc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/index/1/price/asc'.$this->config->item('url_suffix');
			}
		}
		else
		{
			$data['sortday']='themetour/index/1/days/asc'.$this->config->item('url_suffix');
			$data['sortprice']='themetour/index/1/price/asc'.$this->config->item('url_suffix');
			$sort='asc';
		}

		$data['count']=$count;
		$data['sortindex']='selected=selected';
		$data['sortcustomize']='';
		$data['sortfree']='';
		$data['sortgroup']='';
		$data['sortterm']='';
		$data['pagenow']=$page;
		$this->load->library('cimarkdown');
		$this->load->model('webpage');
		$this->webpage=new webpage();
		$type="theme_tour";
		$data['webinfo'] = $this->webpage->getpage($type);
		$data['dess']=$this->show->deslist();
		$data['theme']=$this->show->themelist();
		$data['tour']=$this->show->showthemetour($start,$per_page,$action,$sort,$sorttype);
		$data['dess']=$this->show->deslist();
		$this->load->view('web/landingpage-theme',$data);		
	}
	//定制旅行
	function customize()
	{
		$sorttype='1';
		$this->load->model('show');
		$num=$this->show->totaltour('',$sorttype);
		$per_page=8;
		$count=ceil($num/$per_page);
		$page=$this->uri->segment(3);
		if($page=='')
		{
			$page=1;
		}
		$action=$this->uri->segment(4);
		$sort=$this->uri->segment(5);
		if(isset($page) && $page!='')
		{
			$start=($page*$per_page)-$per_page;
		}
		else
		{
			$start=0;
		}
		
		if(isset($action) &&$action!='')
		{
			$data['page']['first']='themetour/customize/1/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['end']='themetour/customize/'.$count.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			if($page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if($page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='termtour/customize/'.$i.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/customize/'.$pagepre.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['next']='themetour/customize/'.$pagenext.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
		}
		else
		{
			$data['page']['first']='themetour/customize/1'.$this->config->item('url_suffix');
			$data['page']['end']='themetour/customize/'.$count.$this->config->item('url_suffix');
			if(isset($page) && $page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if(isset($page) && $page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='themetour/customize/'.$i.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/customize/'.$pagepre.$this->config->item('url_suffix');
			$data['page']['next']='themetour/customize/'.$pagenext.$this->config->item('url_suffix');
		}
		if(isset($sort) && $sort!='')
		{
			if($sort=='asc')
			{
				$data['sortday']='themetour/customize/1/days/desc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/customize/1/price/desc'.$this->config->item('url_suffix');
			}
			else
			{
				$data['sortday']='themetour/customize/1/days/asc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/customize/1/price/asc'.$this->config->item('url_suffix');
			}
		}
		else
		{
			$data['sortday']='themetour/customize/1/days/asc'.$this->config->item('url_suffix');
			$data['sortprice']='themetour/customize/1/price/asc'.$this->config->item('url_suffix');
			$sort='asc';
		}

		$data['count']=$count;
		$data['pagenow']=$page;
		$data['sortindex']='';
		$data['sortcustomize']='selected=selected';
		$data['sortfree']='';
		$data['sortgroup']='';
		$data['sortterm']='';
		$this->load->library('cimarkdown');
		$this->load->model('webpage');
		$this->webpage=new webpage();
		$type="theme_tour";
		$data['webinfo'] = $this->webpage->getpage($type);
		$data['dess']=$this->show->deslist();
		$data['theme']=$this->show->themelist();
		$data['tour']=$this->show->showthemetour($start,$per_page,$action,$sort,$sorttype);
		$data['dess']=$this->show->deslist();
		$this->load->view('web/landingpage-theme',$data);		
	}
	//自由行
	function free()
	{
		$sorttype='3';
		$this->load->model('show');
		$num=$this->show->totaltour('',$sorttype);
		$per_page=8;
		$count=ceil($num/$per_page);
		$page=$this->uri->segment(3);
		if($page=='')
		{
			$page=1;
		}
		$action=$this->uri->segment(4);
		$sort=$this->uri->segment(5);
		if(isset($page) && $page!='')
		{
			$start=($page*$per_page)-$per_page;
		}
		else
		{
			$start=0;
		}
		
		if(isset($action) &&$action!='')
		{
			$data['page']['first']='themetour/free/1/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['end']='themetour/free/'.$count.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			if($page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if($page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='termtour/free/'.$i.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/free/'.$pagepre.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['next']='themetour/free/'.$pagenext.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
		}
		else
		{
			$data['page']['first']='themetour/free/1'.$this->config->item('url_suffix');
			$data['page']['end']='themetour/free/'.$count.$this->config->item('url_suffix');
			if(isset($page) && $page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if(isset($page) && $page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='themetour/free/'.$i.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/free/'.$pagepre.$this->config->item('url_suffix');
			$data['page']['next']='themetour/free/'.$pagenext.$this->config->item('url_suffix');
		}
		if(isset($sort) && $sort!='')
		{
			if($sort=='asc')
			{
				$data['sortday']='themetour/free/1/days/desc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/free/1/price/desc'.$this->config->item('url_suffix');
			}
			else
			{
				$data['sortday']='themetour/free/1/days/asc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/free/1/price/asc'.$this->config->item('url_suffix');
			}
		}
		else
		{
			$data['sortday']='themetour/free/1/days/asc'.$this->config->item('url_suffix');
			$data['sortprice']='themetour/free/1/price/asc'.$this->config->item('url_suffix');
			$sort='asc';
		}

		$data['count']=$count;
		$data['pagenow']=$page;
		$data['sortindex']='';
		$data['sortcustomize']='';
		$data['sortfree']='selected=selected';
		$data['sortgroup']='';
		$data['sortterm']='';
		$this->load->library('cimarkdown');
		$this->load->model('webpage');
		$this->webpage=new webpage();
		$type="theme_tour";
		$data['webinfo'] = $this->webpage->getpage($type);
		$data['dess']=$this->show->deslist();
		$data['theme']=$this->show->themelist();
		$data['tour']=$this->show->showthemetour($start,$per_page,$action,$sort,$sorttype);
		$data['dess']=$this->show->deslist();
		$this->load->view('web/landingpage-theme',$data);		
	}
	//纯玩跟团
	function group()
	{
		$sorttype='4';
		$this->load->model('show');
		$num=$this->show->totaltour('',$sorttype);
		$per_page=8;
		$count=ceil($num/$per_page);
		$page=$this->uri->segment(3);
		if($page=='')
		{
			$page=1;
		}
		$action=$this->uri->segment(4);
		$sort=$this->uri->segment(5);
		if(isset($page) && $page!='')
		{
			$start=($page*$per_page)-$per_page;
		}
		else
		{
			$start=0;
		}
		
		if(isset($action) &&$action!='')
		{
			$data['page']['first']='themetour/group/1/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['end']='themetour/group/'.$count.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			if($page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if($page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='termtour/group/'.$i.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/group/'.$pagepre.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['next']='themetour/group/'.$pagenext.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
		}
		else
		{
			$data['page']['first']='themetour/group/1'.$this->config->item('url_suffix');
			$data['page']['end']='themetour/group/'.$count.$this->config->item('url_suffix');
			if(isset($page) && $page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if(isset($page) && $page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='themetour/group/'.$i.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/group/'.$pagepre.$this->config->item('url_suffix');
			$data['page']['next']='themetour/group/'.$pagenext.$this->config->item('url_suffix');
		}
		if(isset($sort) && $sort!='')
		{
			if($sort=='asc')
			{
				$data['sortday']='themetour/group/1/days/desc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/group/1/price/desc'.$this->config->item('url_suffix');
			}
			else
			{
				$data['sortday']='themetour/group/1/days/asc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/group/1/price/asc'.$this->config->item('url_suffix');
			}
		}
		else
		{
			$data['sortday']='themetour/group/1/days/asc'.$this->config->item('url_suffix');
			$data['sortprice']='themetour/group/1/price/asc'.$this->config->item('url_suffix');
			$sort='asc';
		}

		$data['count']=$count;
		$data['pagenow']=$page;
		$data['sortindex']='';
		$data['sortcustomize']='';
		$data['sortfree']='';
		$data['sortgroup']='selected=selected';
		$data['sortterm']='';
		$this->load->library('cimarkdown');
		$this->load->model('webpage');
		$this->webpage=new webpage();
		$type="theme_tour";
		$data['webinfo'] = $this->webpage->getpage($type);
		$data['dess']=$this->show->deslist();
		$data['theme']=$this->show->themelist();
		$data['tour']=$this->show->showthemetour($start,$per_page,$action,$sort,$sorttype);
		$data['dess']=$this->show->deslist();
		$this->load->view('web/landingpage-theme',$data);		
	}
	//友途活动线路
	function term()
	{
		$sorttype='0';
		$this->load->model('show');
		$num=$this->show->totaltour('term',$sorttype);
		$per_page=8;
		$count=ceil($num/$per_page);
		$page=$this->uri->segment(3);
		if($page=='')
		{
			$page=1;
		}
		$action=$this->uri->segment(4);
		$sort=$this->uri->segment(5);
		if(isset($page) && $page!='')
		{
			$start=($page*$per_page)-$per_page;
		}
		else
		{
			$start=0;
		}
		
		if(isset($action) &&$action!='')
		{
			$data['page']['first']='themetour/term/1/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['end']='themetour/term/'.$count.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			if($page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if($page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='termtour/term/'.$i.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/term/'.$pagepre.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
			$data['page']['next']='themetour/term/'.$pagenext.'/'.$action.'/'.$sort.$this->config->item('url_suffix');
		}
		else
		{
			$data['page']['first']='themetour/term/1'.$this->config->item('url_suffix');
			$data['page']['end']='themetour/term/'.$count.$this->config->item('url_suffix');
			if(isset($page) && $page>1)
			{
				$pagepre=$page-1;
			}
			else
			{
				$pagepre=1;
			}
			if(isset($page) && $page<$count)
			{
				$pagenext=$page+1;
			}
			else
			{
				$pagenext=$count;
			}
			for($i=1;$i<=$count;$i++)
			{
				$data['page']['plist'][$i]='themetour/term/'.$i.$this->config->item('url_suffix');
			}
			$data['page']['pre']='themetour/term/'.$pagepre.$this->config->item('url_suffix');
			$data['page']['next']='themetour/term/'.$pagenext.$this->config->item('url_suffix');
		}
		if(isset($sort) && $sort!='')
		{
			if($sort=='asc')
			{
				$data['sortday']='themetour/term/1/days/desc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/term/1/price/desc'.$this->config->item('url_suffix');
			}
			else
			{
				$data['sortday']='themetour/term/1/days/asc'.$this->config->item('url_suffix');
				$data['sortprice']='themetour/term/1/price/asc'.$this->config->item('url_suffix');
			}
		}
		else
		{
			$data['sortday']='themetour/term/1/days/asc'.$this->config->item('url_suffix');
			$data['sortprice']='themetour/term/1/price/asc'.$this->config->item('url_suffix');
			$sort='asc';
		}

		$data['count']=$count;
		$data['pagenow']=$page;
		$data['sortindex']='';
		$data['sortcustomize']='';
		$data['sortfree']='';
		$data['sortgroup']='';
		$data['sortterm']='selected=selected';
		$this->load->library('cimarkdown');
		$this->load->model('webpage');
		$this->webpage=new webpage();
		$type="theme_tour";
		$data['webinfo'] = $this->webpage->getpage($type);
		$data['dess']=$this->show->deslist();
		$data['theme']=$this->show->themelist();
		$data['tour']=$this->show->showtermtour($start,$per_page,$action,$sort);
		$data['dess']=$this->show->deslist();
		$this->load->view('web/landingpage-theme',$data);		
	}
}
?>